package telrun.shortnik.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;

import java.sql.Timestamp;
import java.util.Objects;

/**
 * A class describing links
 * A service {@link telrun.shortnik.service.UrlServiceImpl} is provided for working with the class.
 */
@Entity
public class Url {
    /**
     * Link identifier assigned by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    /**
     * This is a shortened link generated by the application.
     */

    @Column(name = "short_url")
    private String shortUrl;
    /**
     * The original link provided by the user.
     */
    @Column(name = "long_url")
    private String longUrl;
    /**
     * The date when the link was created.
     */

    @Column(name = "created_at")
    private Timestamp createdAt;
    /**
     * The date of the last access to the link. Not used in this version of the program.
     */
    @Column(name = "last_use")
    private Timestamp lastUse;
    /**
     * The user can optionally add a description to the link. In the future, this will be useful for adding
     * and storing link statistics.
     */
    @Column(name = "description")
    private String description;
    /**
     * A foreign key indicating the user to whom this link belongs.
     */
    @JsonIgnore
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    public Url(long id, String shortUrl, String longUrl, Timestamp createdAt, Timestamp lastUse, String description, User user) {
        this.id = id;
        this.shortUrl = shortUrl;
        this.longUrl = longUrl;
        this.createdAt = createdAt;
        this.lastUse = lastUse;
        this.description = description;
        this.user = user;
    }

    public Url() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getShortUrl() {
        return shortUrl;
    }

    public void setShortUrl(String shortName) {
        this.shortUrl = shortName;
    }

    public String getLongUrl() {
        return longUrl;
    }

    public void setLongUrl(String longName) {
        this.longUrl = longName;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getLastUse() {
        return lastUse;
    }

    public void setLastUse(Timestamp lastUse) {
        this.lastUse = lastUse;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     * Equals and hashCode are determined by the unique fields id and shortUrl.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Url url = (Url) o;
        return id == url.id && Objects.equals(shortUrl, url.shortUrl);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, shortUrl);
    }



    @Override
    public String toString() {
        return "Url{" +
                "id=" + id +
                ", shortName='" + shortUrl + '\'' +
                ", longName='" + longUrl + '\'' +
                ", createdAt=" + createdAt +
                ", lastUse=" + lastUse +
                ", description='" + description + '\'' +
                ", user=" + user +
                '}';
    }
}
